structA_list = []
structB_list = []

structA_list.append({"apdb_filename" : "/Users/kdrew/scripts/oop/p53_helix.pdb", "structA_vector_ids" : [ 19, 23, 26 ] } )

structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLLLLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDDDDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDDDDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDDDLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDDDLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDDLDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDDLDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDDLLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDDLLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDLDDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDLDDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDLDLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDLDLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDLLDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDLLDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDLLLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DDLLLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLDDDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLDDDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLDDLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLDDLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLDLDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLDLDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLDLLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLDLLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLLDDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLLDDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLLDLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLLDLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLLLDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLLLDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLLLLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/DLLLLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDDDDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDDDDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDDDLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDDDLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDDLDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDDLDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDDLLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDDLLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDLDDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDLDDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDLDLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDLDLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDLLDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDLLDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDLLLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LDLLLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLDDDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLDDDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLDDLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLDDLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLDLDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLDLDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLDLLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLDLLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLLDDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLLDDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLLDLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLLDLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLLLDD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLLLDL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLLLLD_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/rosetta/make_oop_trimers/LLLLLL_ala_6mer_0001_0001.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )

selection_id_type = "RESIDUE"
r_length = 3
save_dir = "/Users/kdrew/data/oop/trimer/d_chiral/trans/match_p53/"
