structA_list = []
structB_list = []

structA_list.append({"apdb_filename" : "/Users/kdrew/scripts/oop/p53_helix.pdb", "structA_vector_ids" : [ 19, 23, 26 ] } )

structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDDDDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDDDDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDDDLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDDDLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDDLDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDDLDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDDLLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDDLLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDLDDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDLDDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDLDLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDLDLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDLLDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDLLDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDLLLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DDLLLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLDDDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLDDDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLDDLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLDDLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLDLDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLDLDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLDLLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLDLLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLLDDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLLDDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLLDLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLLDLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLLLDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLLLDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLLLLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_DLLLLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDDDDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDDDDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDDDLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDDDLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDDLDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDDLDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDDLLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDDLLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDLDDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDLDDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDLDLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDLDLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDLLDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDLLDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDLLLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LDLLLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLDDDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLDDDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLDDLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLDDLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLDLDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLDLDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLDLLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLDLLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLLDDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLLDDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLLDLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLLDLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLLLDD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLLLDL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLLLLD_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/oop_trimer_LLLLLL_cis_trans.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )

selection_id_type = "RESIDUE"
r_length = 3
save_dir = "/Users/kdrew/data/oop/scaffolds/trimer/cis_trans/match_p53/"
