structA_list = []
structB_list = []

structA_list.append({"apdb_filename" : "/Users/kdrew/data/secondary_structure/310_22.pdb", "structA_vector_ids" : [ 3, 4, 5, 6, 7, 8 ,9, 10, 11, 12 ] } )

structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_llll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_llld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_lldl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_lldd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_ldll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_ldld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_lddl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_lddd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )

structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_dlll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_dlld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_dldl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_dldd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_ddll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_ddld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_dddl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_dddd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )

structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_llll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_llld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_lldl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_lldd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_ldll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_ldld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_lddl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_lddd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )

structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_dlll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_dlld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_dldl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_dldd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_ddll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_ddld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_dddl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/idealized/oop_dimer_4PHIhigh_dddd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )

structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_llll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_llld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_lldl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_lldd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_ldll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_ldld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_lddl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_lddd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )

structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_dlll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_dlld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_dldl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_dldd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_ddll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_ddld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_dddl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_dddd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )

#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_llll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_llld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_lldl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_lldd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_ldll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_ldld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_lddl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_lddd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )

#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_dlll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_dlld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_dldl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_dldd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_ddll.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_ddld.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_dddl.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )
#structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/idealized/oop_dimer_cis_4thPHIhigh_dddd.pdb", "structB_vector_ids" : [ 1, 2, 3, 4 ] } )

selection_id_type = "RESIDUE"
r_length = 4
save_dir = "/Users/kdrew/data/oop/dimer/d_chiral/cis_trans/match_310/"
