structA_list = []
structB_list = []

structA_list.append({"apdb_filename" : "/Users/kdrew/scripts/ha_scripts/HADesigns/HB80b.pdb", "structA_vector_ids" : [ 285, 289, 304 ] } )

structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDDDDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDDDDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDDDLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDDDLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDDLDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDDLDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDDLLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDDLLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDLDDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDLDDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDLDLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDLDLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDLLDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDLLDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDLLLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DDLLLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLDDDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLDDDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLDDLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLDDLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLDLDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLDLDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLDLLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLDLLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLLDDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLLDDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLLDLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLLDLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLLLDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLLLDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLLLLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_DLLLLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDDDDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDDDDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDDDLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDDDLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDDLDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDDLDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDDLLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDDLLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDLDDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDLDDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDLDLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDLDLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDLLDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDLLDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDLLLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LDLLLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLDDDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLDDDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLDDLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLDDLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLDLDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLDLDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLDLLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLDLLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLLDDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLLDDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLLDLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLLDLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLLLDD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLLLDL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLLLLD_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )
structB_list.append({"bpdb_filename" : "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/oop_trimer_LLLLLL_trans_cis.pdb", "structB_vector_ids" : [ 2, 3, 4, 5, 6, 7 ] } )

selection_id_type = "RESIDUE"
r_length = 3
save_dir = "/Users/kdrew/data/oop/scaffolds/trimer/trans_cis/match_p53/"
